### ISSUE TITLE
[BUG] 1.0.0: The test step_callback fails

### ISSUE THREAD

**Issue by yurivict** [bluescarni/heyoka#338] opened 2023-08-11 05:44 UTC
**Describe the bug**
```
108/123 Test #108: step_callback ....................***Failed    0.63 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
step_callback is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
step_callback basics
-------------------------------------------------------------------------------
/usr/ports/math/heyoka/work/heyoka-1.0.0/test/step_callback.cpp:49
...............................................................................

/usr/ports/math/heyoka/work/heyoka-1.0.0/test/step_callback.cpp:58: FAILED:
  REQUIRE_THROWS_AS( step_cb(ta), std::bad_function_call )
due to unexpected exception with message:
  std::exception

===============================================================================
test cases:  3 |  2 passed | 1 failed
assertions: 31 | 30 passed | 1 failed
```

**Environment (please complete the following information):**
 - OS: FreeBSD 13.2
 - Installation method: port
 - Version: 1.0.0

**Comment by bluescarni** [comment] 2023-08-11 08:36
@yurivict the test is complaining that a generic ``std::exception`` is thrown instead of the more specific ``std::bad_function_call`` (which does inherit from ``std::exception``):

https://en.cppreference.com/w/cpp/utility/functional/bad_function_call

I don't understand how this is possible, since the code explicitly throws ``std::bad_function_call``:

https://github.com/bluescarni/heyoka/blob/master/src/step_callback.cpp#L74

I can amend the test to just check for *something* to be thrown, but I don't understand why this is failing only on FreeBSD.

If you replace the failing line with:

```c++
REQUIRE_THROWS_AS( step_cb(ta), std::exception )
```

and equivalently for the next line:

```c++
REQUIRE_THROWS_AS(step_cb.pre_hook(ta), std::exception);
```

Does this fix the failure?

**Comment by yurivict** [comment] 2023-08-11 08:46
> I can amend the test to just check for something to be thrown, but I don't understand why this is failing only on FreeBSD.

It's better to understand why this is failing exactly.
I'll do some experiments too.

**Comment by yurivict** [comment] 2023-08-11 08:52
This code catches ```std::bad_function_call``` as thrown on FreeBSD:
```
int main() {
        try {
                throw std::bad_function_call(); 
        } catch (std::bad_function_call e) {
                std::cout << "caught bad_function_call" << std::endl;
        } catch (std::exception e) {
                std::cout << "caught exception" << std::endl;
        }
}
```

The order of catch instructions is important.

**Comment by bluescarni** [comment] 2023-08-11 09:03
> This code catches `std::bad_function_call` as thrown on FreeBSD:
> 
> ```
> #include <exception>
> #include <iostream>
> 
> int main() {
>         try {
>                 throw std::bad_function_call(); 
>         } catch (std::bad_function_call e) {
>                 std::cout << "caught bad_function_call" << std::endl;
>         } catch (std::exception e) {
>                 std::cout << "caught exception" << std::endl;
>         }
> }
> ```
> 
> The order of catch instructions is important.

Thanks for checking! So it looks like the problem is not ``std::bad_function_call`` per se.

I just noticed that there is a similar usage of ``std::bad_function_call`` in the ``callable`` class. E.g., see this unit test:

https://github.com/bluescarni/heyoka/blob/master/test/callable.cpp#L154

Does this test pass fine on your setup?

**Comment by yurivict** [comment] 2023-08-11 09:18
> Does this test pass fine on your setup?

All other tests pass.

**Comment by bluescarni** [comment] 2023-08-11 10:05
@yurivict would you mind checking if the attached patch makes any difference?

https://gist.github.com/bluescarni/67b13d5959535ae2f58754741b1f8a73

**Comment by yurivict** [comment] 2023-08-11 10:35
The same test failure happens with this patch.

**Comment by bluescarni** [comment] 2023-08-11 11:46
Ok, thanks for checking.

Under the assumption that FreeBSD is using libc++ as its C++ standard library... (otherwise, disregard everything I am writing here).

I noticed there is a difference in the implementation of exceptions classes in my local copy of libc++ (16.0.4). Specifically, an exception like ``std::invalid_argument`` is implemented as this (from the ``<stdexcept>`` header file):

```c++
class _LIBCPP_EXCEPTION_ABI invalid_argument
    : public logic_error
{
...
```

Whereas ``std::bad_function_call`` is implemented like this (from the ``<functional>`` header):

```c++
class bad_function_call
    : public exception
{
...
```

The important difference is the lack of ``_LIBCPP_EXCEPTION_ABI`` macro in the implementation of ``std::bad_function_call``. This macro eventually expands to ``__declspec(dllexport)`` or  ``__attribute__((__visibility__(vis)))``, depending on compiler/platform. These attribute are used to set the visibility of symbols across DLLs. In particular, exceptions classes should always be marked as visible otherwise there could be issues catching exceptions across DLL boundaries. See the discussion here:

https://gcc.gnu.org/wiki/Visibility

(in particular the "Problems with C++ exceptions" section).

So, could this be a bug in libc++? Do you have any way of finding out?

**Comment by bluescarni** [comment] 2023-08-11 11:51
@yurivict sorry disregard the above post, it turns out I was not looking at the correct file... ``bad_function_call`` does have the correct attribute set.

**Comment by bluescarni** [comment] 2023-08-11 11:53
@yurivict see also this report: https://github.com/llvm/llvm-project/issues/54863#issuecomment-1096977132

**Comment by yurivict** [comment] 2023-08-11 16:59
Hi @bluescarni ,

Do you have a C++ testcase that fails?

Yuri

**Comment by bluescarni** [comment] 2023-08-14 09:22
@yurivict could you tell me if the libc++ version you are using contains the symbol for ``std::bad_function_call``? I.e., does something like

```bash
$ readelf -s -C --wide /usr/lib/libc++.so.1.0 |grep -i bad_function
```

return something?

**Comment by yurivict** [comment] 2023-08-14 16:47
```
$ readelf -s  --wide /usr/lib/libc++.so.1 |grep -i bad_function
   514: 00000000000fcb68    24 OBJECT  GLOBAL DEFAULT   22 _ZTINSt3__117bad_function_callE
  1776: 00000000000484c6    28 OBJECT  GLOBAL DEFAULT   10 _ZTSNSt3__117bad_function_callE
  2150: 00000000000fcb40    40 OBJECT  GLOBAL DEFAULT   22 _ZTVNSt3__117bad_function_callE
  2199: 00000000000a2420    10 FUNC    GLOBAL DEFAULT   14 _ZNSt3__117bad_function_callD2Ev
  2275: 00000000000a2420    10 FUNC    GLOBAL DEFAULT   14 _ZNSt3__117bad_function_callD1Ev
  2348: 00000000000a2430    28 FUNC    GLOBAL DEFAULT   14 _ZNSt3__117bad_function_callD0Ev
```

**Comment by bluescarni** [comment] 2023-08-21 12:08
@yurivict would you mind checking also if ``libheyoka.so`` contains the symbol for ``bad_function_call``? I.e., something like

```bash
$ readelf -s -C --wide libheyoka.so|grep -i bad_func
```

executed from the ``build`` directory of heyoka?

**Comment by bluescarni** [comment] 2024-06-13 20:08
@yurivict are you still experiencing this issue on recent heyoka versions?

**Comment by bluescarni** [comment] 2024-08-04 18:38
Closing this for now, please re-open if needed.

**Closed by bluescarni** 2024-08-04 18:38 UTC
Labels: bug
